image: python:latest
pages:
  stage: deploy
  script:
    - pip install mkdocs-material
    - pip install fontawesome-markdown
    - mkdocs build --site-dir public
  when: manual
  artifacts:
    paths:
      - public
